version: "3.8"
services:
  server:
    build: ./server
    stdin_open: true
    tty: true
    networks:
      - chatnet

  client:
    build: ./client
    stdin_open: true
    tty: true
    depends_on:
      - server
    networks:
      - chatnet

networks:
  chatnet:
    driver: bridge